repos:
- repo: https://github.com/slessans/pre-commit-swift-format
  rev: ""
  hooks:
    - id: swift-format
      args: ["--configuration", ".swift-format"]
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
    - id: cmake-format
