repos:

- repo: local
  hooks:
    - id: swift-format
      name: swift-format
      language: system
      entry: swift-format format --in-place --configuration .swift-format --recursive .
      require_serial: true
      types: [swift]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
    - id: cmake-format
