repos:

- repo: local
  hooks:
    - id: swift-format
      name: swift-format
      language: system
      entry: bash -c 'swift-format format --in-place --configuration .swift-format --recursive . || (echo "Style checks failed, please install pre-commit and run pre-commit run --all and push the change"; echo ""; git diff; exit 1)'

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
    - id: cmake-format
