#include <Cmlx/mlx-c-mlx.h>
#include <Cmlx/mlx-c-transforms_impl.h>
#include <Cmlx/mlx-c-linalg.h>
#include <Cmlx/mlx-c-fast.h>

#include <Cmlx/mlx-api.h>
#include <Cmlx/mlx-array.h>
#include <Cmlx/mlx-backend-cuda-cuda.h>
#include <Cmlx/mlx-backend-metal-metal.h>
#include <Cmlx/mlx-compile.h>
#include <Cmlx/mlx-device.h>
#include <Cmlx/mlx-distributed-distributed.h>
#include <Cmlx/mlx-distributed-ops.h>
#include <Cmlx/mlx-einsum.h>
#include <Cmlx/mlx-export.h>
#include <Cmlx/mlx-fast.h>
#include <Cmlx/mlx-fft.h>
#include <Cmlx/mlx-io.h>
#include <Cmlx/mlx-linalg.h>
#include <Cmlx/mlx-memory.h>
#include <Cmlx/mlx-ops.h>
#include <Cmlx/mlx-random.h>
#include <Cmlx/mlx-stream.h>
#include <Cmlx/mlx-transforms.h>
#include <Cmlx/mlx-utils.h>
#include <Cmlx/mlx-version.h>
#include <Cmlx/mlx-allocator.h>
#include <Cmlx/mlx-dtype.h>
#include <Cmlx/mlx-event.h>
#include <Cmlx/mlx-small_vector.h>
#include <Cmlx/mlx-types-complex.h>
#include <Cmlx/mlx-types-half_types.h>
#include <Cmlx/mlx-types-bf16.h>
#include <Cmlx/mlx-types-fp16.h>
#include <Cmlx/mlx-io-load.h>
#include <Cmlx/mlx-export_impl.h>
#include <Cmlx/mlx-threadpool.h>
#include <Cmlx/mlx-scheduler.h>
#include <Cmlx/mlx-primitives.h>
#include <Cmlx/mlx-backend-metal-device.h>
#include <Cmlx/mlx-backend-metal-utils.h>
#include <Cmlx/mlx-backend-common-utils.h>
#include <Cmlx/mlx-backend-cpu-encoder.h>
#include <Cmlx/mlx-backend-gpu-eval.h>
#include <Cmlx/Metal.hpp>
