name: 'Build and Test on macOS'
description: 'Build and test MLX on macOS'

runs:
  using: "composite"
  steps:
    - name: Run style checks
      shell: sh
      run:
      - |
        pre-commit run --all || (echo "Style checks failed, please install pre-commit and run pre-commit run --all and push the change"; echo ""; git --no-pager diff; exit 1)
    
    - name: Run Tests (Xcode, macOS)
      shell: sh
      run:
      - |
        xcodebuild -version
        xcrun --show-sdk-build-version
        swift --version
        xcodebuild test -scheme mlx-swift-Package -destination 'platform=OS X'

    - name: Build (cmake)
      shell: sh
      run:
      - |
        rm -rf build
        mkdir build
        cd build
        cmake .. -G Ninja
        ninja

