name: 'Setup macOS Environment'
description: 'Install dependencies for macOS builds'

inputs:
    python-version:
      description: 'Python version to use'
      required: false
      default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Verify MetalToolchain installed
      shell: bash
      run: xcodebuild -showComponent MetalToolchain
    
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
          python-version: ${{ inputs.python-version }}
          activate-environment: true

    - name: Setup swift-format
      shell: sh
      run:
      - |
        uv pip install pre-commit
        brew install swift-format

    - name: Setup cmake
      shell: sh
      run:
      - |
        brew install cmake ninja
