name: Build and Test

on: pull_request

permissions:
  contents: read

jobs:

  mac_build_and_test:
    if: github.repository == 'ml-explore/mlx-swift'
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Verify MetalToolchain installed
        shell: bash
        run: xcodebuild -showComponent MetalToolchain

      - name: Setup cmake
        shell: sh
        run: |
          brew install cmake ninja

      - name: Build SwiftPM (Xcode, macOS)
        env:
          DEVELOPER_DIR: /Applications/Xcode-latest.app
        shell: sh
        run: |
          ls /Applications | grep -i Xcode
          xcodebuild -version
          swift --version
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          xcodebuild build-for-testing -scheme mlx-swift-Package -destination 'platform=macOS'

      - name: Run Tests SwiftPM (Xcode, macOS)
        shell: sh
        run: |
          xcrun xctest ~/Library/Developer/Xcode/DerivedData/mlx-swift-*/Build/Products/Debug/CmlxTests.xctest
          xcrun xctest ~/Library/Developer/Xcode/DerivedData/mlx-swift-*/Build/Products/Debug/MLXTests.xctest

      - name: Build xcodeproj (Xcode, macOS)
        shell: sh
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          cd xcode
          xcodebuild build-for-testing -scheme MLX -destination 'platform=macOS'

      - name: Run Tests xcodeproj (Xcode, macOS)
        working-directory: xcode
        run: ../.github/scripts/run-xcode-tests.sh

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
            /Users/runner/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
            ~/Library/Logs/DiagnosticReports/*
          retention-days: 7

